import express from "express";
import { protect } from "../middleware/authMiddleware.js";
import { allowRoles } from "../middleware/roleMiddleware.js";
import { adminSummary, listUsers, updateUserStatus, listAdminRequests, listAdminApplications } from "../controllers/adminController.js";
import { listAdminAlerts, listEligibleAlertRecipients, adminRecalculateAchievements, createEmergencyContact, updateEmergencyContact, listEmergencyContactAudit, listAdminEmergencyContacts, listAbuseReports, reviewAbuseReport } from "../controllers/emergencyController.js";

const router = express.Router();
router.use(protect, allowRoles("ADMIN"));
router.get("/summary", adminSummary);
router.get("/users", listUsers);
router.patch("/users/:id/status", updateUserStatus);
router.get("/requests", listAdminRequests);
router.get("/applications", listAdminApplications);
router.get("/emergency-alerts", listAdminAlerts);
router.get("/emergency-eligible-users", listEligibleAlertRecipients);
router.get("/emergency-reports", listAbuseReports);
router.patch("/emergency-reports/:id", reviewAbuseReport);
router.get("/emergency-contacts", listAdminEmergencyContacts);
router.get("/emergency-contacts/audit", listEmergencyContactAudit);
router.post("/emergency-contacts", createEmergencyContact);
router.patch("/emergency-contacts/:key", updateEmergencyContact);
router.post("/users/:userId/recalculate-achievements", adminRecalculateAchievements);
export default router;
