import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowUpRight, HandHeart, Loader2, Users } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { apiFetch } from '../lib/api'

export default function HomePage() {
  const { user } = useAuth(); const [requests, setRequests] = useState([]); const [opportunities, setOpportunities] = useState([]); const [donations, setDonations] = useState([]); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([apiFetch('/requests/my'), apiFetch('/opportunities'), apiFetch('/donations/my')]).then(([r, o, d]) => { setRequests(r.data); setOpportunities(o.data); setDonations(d.data) }).catch((requestError) => console.error(requestError.message)).finally(() => setLoading(false)) }, [])
  const stats = [{ label: 'My requests', value: requests.length, icon: AlertTriangle, color: 'text-red-400' }, { label: 'Open opportunities', value: opportunities.length, icon: Users, color: 'text-emerald-400' }, { label: 'My pledges', value: donations.length, icon: HandHeart, color: 'text-cyan-400' }]
  return <div className="relief-page relief-page--home mx-auto min-h-[calc(100vh-12rem)] max-w-7xl space-y-8 px-4 py-10 sm:px-6 lg:px-8"><header className="flex flex-col gap-4 rounded-3xl border border-slate-800 bg-slate-900/75 p-6 shadow-xl md:flex-row md:items-center md:justify-between"><div><span className="text-xs font-bold uppercase tracking-widest text-cyan-400">Operations center</span><h1 className="mt-2 text-3xl font-black text-white">Welcome, {user?.name || user?.organizationName}</h1><p className="mt-2 text-sm text-slate-400">Your live coordination overview, backed by ReliefGrid data.</p></div><div className="flex flex-wrap gap-2"><Link to="/request" className="rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white">Request help</Link><Link to="/donate" className="rounded-xl bg-slate-800 px-4 py-2.5 text-xs font-bold text-white">Pledge support</Link></div></header>{loading ? <Loader2 className="h-6 w-6 animate-spin text-cyan-400" /> : <><div className="grid gap-4 sm:grid-cols-3">{stats.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><Icon className={`h-5 w-5 ${color}`} /><p className="mt-4 text-3xl font-black text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-white">Recent requests</h2><Link to="/request" className="text-xs text-cyan-400">View all</Link></div>{requests.slice(0, 5).map((item) => <div key={item._id} className="flex items-center justify-between border-b border-slate-800 py-3 last:border-0"><div><p className="text-sm font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.location} · {item.category}</p></div><span className="text-[10px] font-bold text-cyan-300">{item.status}</span></div>)}{requests.length === 0 && <p className="text-sm text-slate-400">Your request queue is clear.</p>}</section><section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-white">Volunteer response</h2><Link to="/volunteer" className="text-xs text-emerald-400">Explore</Link></div>{opportunities.slice(0, 5).map((item) => <div key={item._id} className="flex items-center justify-between border-b border-slate-800 py-3 last:border-0"><div><p className="text-sm font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.location} · {item.joinedVolunteers?.length || 0}/{item.requiredVolunteers} joined</p></div><ArrowUpRight className="h-4 w-4 text-emerald-400" /></div>)}{opportunities.length === 0 && <p className="text-sm text-slate-400">No opportunities published yet.</p>}</section></div></>}</div>
}
