import { useState } from 'react'
import { CheckCircle2, Loader2, UserRound } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { apiFetch } from '../lib/api'

const fields = ['name', 'organizationName', 'phone', 'location']
const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3.5 py-2.5 text-sm text-white outline-none focus:border-cyan-400'
export default function ProfilePage() {
  const { user, setUser } = useAuth(); const [form, setForm] = useState({ name: user?.name || '', organizationName: user?.organizationName || '', phone: user?.phone || '', location: user?.location || '' }); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '' }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const data = await apiFetch('/users/me', { method: 'PATCH', body: JSON.stringify(form) }); setUser(data.data); setMessage('Profile updated.') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const changePassword = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const data = await apiFetch('/users/me/password', { method: 'PATCH', body: JSON.stringify(passwords) }); setMessage(data.message); setPasswords({ currentPassword: '', newPassword: '' }) } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <div className="mx-auto min-h-[calc(100vh-12rem)] max-w-2xl space-y-6 px-4 py-10 sm:px-6 lg:px-8"><header className="mb-6"><UserRound className="h-8 w-8 text-cyan-400" /><h1 className="mt-3 text-3xl font-black text-white">Profile</h1><p className="mt-2 text-sm text-slate-400">Keep your contact details current for relief coordination.</p></header>{message && <p className="flex gap-2 rounded-xl border border-emerald-500/30 bg-emerald-950/50 p-3 text-sm text-emerald-200"><CheckCircle2 className="h-4 w-4" />{message}</p>}{error && <p className="rounded-xl border border-red-500/30 bg-red-950/50 p-3 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900/75 p-6">{fields.map((field) => <label key={field} className="block text-xs font-semibold capitalize text-slate-300">{field.replace('organizationName', 'organization name')}<input className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3.5 py-2.5 text-sm text-white outline-none focus:border-cyan-400" value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required={field !== 'organizationName'} /></label>)}<div className="grid gap-4 text-xs text-slate-400 sm:grid-cols-2"><p>Email<br /><strong className="text-white">{user?.email}</strong></p><p>Role<br /><strong className="text-cyan-300">{user?.role}</strong></p><p>Verification<br /><strong className="text-emerald-300">{user?.verificationStatus}</strong></p></div><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-600 py-3 text-sm font-bold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Save profile</button></form><form onSubmit={changePassword} className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900/75 p-6"><h2 className="text-lg font-bold text-white">Change password</h2><input required type="password" placeholder="Current password" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} className={inputClass} /><input required minLength="8" type="password" placeholder="New password" value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} className={inputClass} /><button disabled={saving} className="w-full rounded-xl border border-cyan-500/40 py-3 text-sm font-bold text-cyan-300 disabled:opacity-50">Update password</button></form></div>
}
