import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, CheckCircle2, Loader2, MapPin, Send } from 'lucide-react'
import { apiFetch } from '../lib/api'

const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3.5 py-2.5 text-sm text-white outline-none focus:border-cyan-400'

export default function RequestPage() {
  const [requests, setRequests] = useState([])
  const [form, setForm] = useState({ title: '', category: 'Medical', urgency: 'HIGH', description: '', location: '', latitude: '', longitude: '', contactPhone: '', peopleAffected: 1, requiredResources: '' })
  const [state, setState] = useState({ loading: true, submitting: false, error: '', success: '' })
  const load = async () => { try { const data = await apiFetch('/requests/my'); setRequests(data.data) } catch (error) { setState((s) => ({ ...s, error: error.message })) } finally { setState((s) => ({ ...s, loading: false })) } }
  useEffect(() => { load() }, [])
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setState({ loading: false, submitting: true, error: '', success: '' }); try { await apiFetch('/requests', { method: 'POST', body: JSON.stringify({ ...form, peopleAffected: Number(form.peopleAffected) }) }); setForm({ ...form, title: '', description: '', location: '', requiredResources: '' }); setState({ loading: false, submitting: false, error: '', success: 'Request submitted to the relief coordination queue.' }); load() } catch (error) { setState({ loading: false, submitting: false, error: error.message, success: '' }) } }
  return <div className="relief-page relief-page--request mx-auto min-h-[calc(100vh-12rem)] max-w-6xl space-y-8 px-4 py-10 sm:px-6 lg:px-8">
    <header><span className="text-xs font-bold uppercase tracking-widest text-red-400">Priority channel</span><h1 className="mt-2 text-3xl font-black text-white">Request emergency help</h1><p className="mt-2 text-sm text-slate-400">Submit a real relief request for verified responders to review.</p></header>
    {state.error && <div className="flex gap-2 rounded-xl border border-red-500/30 bg-red-950/50 p-3 text-sm text-red-200"><AlertTriangle className="h-4 w-4" />{state.error}</div>}
    {state.success && <div className="flex gap-2 rounded-xl border border-emerald-500/30 bg-emerald-950/50 p-3 text-sm text-emerald-200"><CheckCircle2 className="h-4 w-4" />{state.success}</div>}
    <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-800 bg-slate-900/80 p-6">
      <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-xs font-semibold text-slate-300">Request title<input className={inputClass} name="title" value={form.title} onChange={update} required placeholder="What help is needed?" /></label><label className="text-xs font-semibold text-slate-300">Category<select className={inputClass} name="category" value={form.category} onChange={update}>{['Food','Water','Medical','Shelter','Rescue','Transport','Other'].map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold text-slate-300">Urgency<select className={inputClass} name="urgency" value={form.urgency} onChange={update}>{['LOW','MEDIUM','HIGH','CRITICAL'].map((x) => <option key={x}>{x}</option>)}</select></label></div>
      <label className="block text-xs font-semibold text-slate-300">Situation description<textarea className={inputClass} name="description" value={form.description} onChange={update} required rows="4" placeholder="Describe the situation and immediate risks." /></label>
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-300">Location<input className={inputClass} name="location" value={form.location} onChange={update} required placeholder="Shelter, district, landmark" /></label><label className="text-xs font-semibold text-slate-300">Contact phone<input className={inputClass} name="contactPhone" value={form.contactPhone} onChange={update} required placeholder="Reachable phone number" /></label><label className="text-xs font-semibold text-slate-300">Latitude (optional)<input className={inputClass} type="number" min="-90" max="90" step="any" name="latitude" value={form.latitude} onChange={update} placeholder="Exact latitude" /></label><label className="text-xs font-semibold text-slate-300">Longitude (optional)<input className={inputClass} type="number" min="-180" max="180" step="any" name="longitude" value={form.longitude} onChange={update} placeholder="Exact longitude" /></label><label className="text-xs font-semibold text-slate-300">People affected<input className={inputClass} type="number" min="1" name="peopleAffected" value={form.peopleAffected} onChange={update} /></label><label className="text-xs font-semibold text-slate-300">Resources needed<input className={inputClass} name="requiredResources" value={form.requiredResources} onChange={update} placeholder="Water, kits, transport..." /></label></div>
      <button disabled={state.submitting} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 py-3 text-sm font-bold text-white disabled:opacity-60"><Send className="h-4 w-4" />{state.submitting ? <><Loader2 className="h-4 w-4 animate-spin" />Submitting...</> : 'Broadcast request'}</button>
    </form><section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold text-white">My requests</h2><Link className="text-xs text-cyan-400" to="/home">Dashboard</Link></div>{state.loading ? <Loader2 className="h-5 w-5 animate-spin text-cyan-400" /> : requests.length === 0 ? <p className="text-sm text-slate-400">No requests submitted yet.</p> : <div className="space-y-3">{requests.map((request) => <article key={request._id} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold text-white">{request.title}</h3><span className="text-[10px] font-bold text-cyan-300">{request.status}</span></div><p className="mt-2 flex items-center gap-1 text-xs text-slate-400"><MapPin className="h-3 w-3" />{request.location}</p><p className="mt-2 text-xs text-slate-500">{request.category} · {request.urgency} · {request.peopleAffected} affected</p></article>)}</div>}</section></div>
  </div>
}
